(async()=>{try{
const b=atob(window.DATA_GZ||"");const bytes=new Uint8Array(b.length);for(let i=0;i<b.length;i++)bytes[i]=b.charCodeAt(i);
const ds=new DecompressionStream("gzip");const txt=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).text();
window.RAW_MONEY_DATA=JSON.parse(txt);

const R=window.RAW_MONEY_DATA;
const DATA={order:R.order,months:{}};
R.order.forEach(k=>{const x=R.months[k];DATA.months[k]={...x,
startAccounts:{'Regular Savings':x.sa[0],'Bright Future Savings':x.sa[1],'Debit Account':x.sa[2]},
endAccounts:{'Regular Savings':x.ea[0],'Bright Future Savings':x.ea[1],'Debit Account':x.ea[2]},
tx:x.tx.map(t=>({date:`${k}-${String(t[0]).padStart(2,'0')}`,account:R.accounts[t[1]],merchant:R.merchants[t[2]],description:R.merchants[t[2]],amount:t[3],category:R.cats[t[4]],major:t[5],direct:t[6]?'Yes':'No',review:['Other Spending','External Transfer','Refund / Reimbursement','Other Deposit','External Transfer / Deposit'].includes(R.cats[t[4]])}))};});
const D=DATA.months, order=DATA.order, latest=order[order.length-1], sel=document.getElementById('month');
const K401=[{date:'Dec 31, 2025',balance:4061.56,contributions:623.04,gain:71.76},{date:'Mar 31, 2026',balance:7069.06,contributions:3037.47,gain:-29.97},{date:'Jun 30, 2026',balance:8708.28,contributions:787.54,gain:851.68}];
const AUTOLOAN=[{date:'Nov 17, 2025',balance:13562.66,payment:258.56},{date:'Dec 17, 2025',balance:13299.50,payment:263.16},{date:'Jan 15, 2026',balance:13031.81,payment:267.69},{date:'Feb 18, 2026',balance:12776.37,payment:255.44},{date:'Mar 17, 2026',balance:12499.99,payment:276.38},{date:'Apr 16, 2026',balance:12230.02,payment:269.97},{date:'May 15, 2026',balance:11955.72,payment:274.30},{date:'Jun 17, 2026',balance:11689.92,payment:265.80},{date:'Jul 16, 2026',balance:13365.02,payment:273.90,note:'Before CPI insurance refund'},{date:'Jul 20, 2026',balance:11416.02,payment:0,note:'$1,949 CPI insurance charge fully refunded'}];
const ROTH=[{date:'Nov 30, 2025',balance:13668.75},{date:'Dec 31, 2025',balance:13688.39},{date:'Jan 31, 2026',balance:14004.43},{date:'Feb 28, 2026',balance:14140.20},{date:'Mar 31, 2026',balance:13405.30},{date:'Apr 30, 2026',balance:14591.68},{date:'May 31, 2026',balance:15254.19},{date:'Jun 30, 2026',balance:15300.03},{date:'Jul 31, 2026',balance:15080.31}];
const CREDIT_HISTORY={'2025-11':[{name:'Capital One QuicksilverOne',balance:308.80,asof:'Nov 20, 2025'},{name:'Amazon / Chase',balance:723.12,asof:'Nov 4, 2025'},{name:'Members 1st Visa Signature',balance:0,asof:'Nov 2, 2025'}],'2025-12':[{name:'Capital One QuicksilverOne',balance:249.45,asof:'Dec 21, 2025'},{name:'Amazon / Chase',balance:613.82,asof:'Dec 4, 2025'},{name:'Members 1st Visa Signature',balance:21.60,asof:'Dec 1, 2025'}],'2026-01':[{name:'Capital One QuicksilverOne',balance:208.25,asof:'Jan 21, 2026'},{name:'Amazon / Chase',balance:839.88,asof:'Jan 4, 2026'},{name:'Members 1st Visa Signature',balance:43.76,asof:'Jan 1, 2026'}],'2026-02':[{name:'Capital One QuicksilverOne',balance:977.66,asof:'Feb 18, 2026'},{name:'Amazon / Chase',balance:618.71,asof:'Feb 4, 2026'},{name:'Members 1st Visa Signature',balance:86.18,asof:'Feb 1, 2026'}],'2026-03':[{name:'Capital One QuicksilverOne',balance:844.58,asof:'Mar 21, 2026'},{name:'Amazon / Chase',balance:535.21,asof:'Mar 4, 2026'},{name:'Members 1st Visa Signature',balance:-35.40,asof:'Mar 1, 2026'}],'2026-04':[{name:'Capital One QuicksilverOne',balance:556.23,asof:'Apr 20, 2026'},{name:'Amazon / Chase',balance:298.72,asof:'Apr 4, 2026'},{name:'Members 1st Visa Signature',balance:37.77,asof:'Apr 1, 2026'}],'2026-05':[{name:'Capital One QuicksilverOne',balance:534.05,asof:'May 21, 2026'},{name:'Amazon / Chase',balance:0,asof:'May 4, 2026'},{name:'Members 1st Visa Signature',balance:0,asof:'May 1, 2026'}],'2026-06':[{name:'Capital One QuicksilverOne',balance:699.30,asof:'Jun 20, 2026'},{name:'Amazon / Chase',balance:925.35,asof:'Jun 4, 2026'},{name:'Members 1st Visa Signature',balance:0,asof:'Jun 1, 2026'}],'2026-07':[{name:'Capital One QuicksilverOne',balance:519.26,asof:'Jul 21, 2026'},{name:'Amazon / Chase',balance:157.20,asof:'Jul 4, 2026'},{name:'Members 1st Visa Signature',balance:0,asof:'Jul 1, 2026'}]};
const AUTO_ORIGINAL=20591.91,AUTO_PAYMENT=350;
const USER_CATS=['Income','Housing','Groceries & Dining','Shopping','Vehicle & Transportation','Bills & Utilities','Subscriptions & Digital','Home','Entertainment','Health','Travel','Gifts & Donations','Personal Care','Education','Savings / Investing','Debt Payment','Other','Needs Review'];
const MAP={'Income':'Income','Other Income':'Income','Housing':'Housing','Rent':'Housing','Groceries & Dining':'Groceries & Dining','Food & Dining':'Groceries & Dining','Dining / Delivery':'Groceries & Dining','Groceries':'Groceries & Dining','Dining':'Groceries & Dining','Food':'Groceries & Dining','Shopping':'Shopping','Shopping / Retail':'Shopping','Retail':'Shopping','Vehicle & Transportation':'Vehicle & Transportation','Transportation':'Vehicle & Transportation','Gas / Convenience':'Vehicle & Transportation','Gas':'Vehicle & Transportation','Parking':'Vehicle & Transportation','Transit':'Vehicle & Transportation','Bills & Utilities':'Bills & Utilities','Phone':'Bills & Utilities','Utilities':'Bills & Utilities','Subscriptions & Digital':'Subscriptions & Digital','Software / Digital':'Subscriptions & Digital','Auto / Car Wash':'Subscriptions & Digital','Entertainment / Subscriptions':'Subscriptions & Digital','Home':'Home','Entertainment':'Entertainment','Entertainment / Activities':'Entertainment','Health':'Health','Medical':'Health','Travel':'Travel','Gifts & Donations':'Gifts & Donations','Gifts':'Gifts & Donations','Donations':'Gifts & Donations','Personal Care':'Personal Care','Education':'Education','Savings / Investing':'Savings / Investing','Savings':'Savings / Investing','Investing':'Savings / Investing','Debt Payment':'Debt Payment','Credit Card Payment':'Debt Payment','Other':'Other','Other Spending':'Other','Needs Review':'Needs Review','Person-to-Person':'Needs Review','External Transfer':'Needs Review','External Transfer / Deposit':'Needs Review','Other Deposit':'Needs Review','Refund / Reimbursement':'Needs Review','Internal Transfer':'Needs Review'};
const fmt=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0),fmt2=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0),dateFmt=s=>{const[y,m,d]=s.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(y,m-1,d))};
const escapeHtml=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function canonical(c){return USER_CATS.includes(c)?c:(MAP[c]||'Needs Review')}
function source(t){return(t.description||t.merchant||'Unknown source').trim()}
function isP2P(t){return /venmo|zelle|cash ?app|apple cash|person-to-person/i.test(source(t))}
function txKey(t){return'catOverride:'+t.date+'|'+t.account+'|'+t.amount+'|'+source(t)}
function merchantKey(t){return'merchantRule:'+source(t).toUpperCase().replace(/\s+/g,' ').trim()}
function effective(t){const one=localStorage.getItem(txKey(t));if(one)return canonical(one);if(!isP2P(t)){const rule=localStorage.getItem(merchantKey(t));if(rule)return canonical(rule)}const s=source(t).toUpperCase();if(isP2P(t))return'Needs Review';if(/JWALES|JOHNSON.*WALES/.test(s))return'Education';if(/WHOLE ?FOODS/.test(s))return'Groceries & Dining';if(/AMAZON PRIME/.test(s))return'Subscriptions & Digital';if(/AMAZON|AMZN/.test(s))return'Shopping';if(t.amount<0&&Math.abs(Math.abs(t.amount)-350)<.01&&/MEMBERS ?1ST|MEMBERS FIRST/.test(s))return'Vehicle & Transportation';return canonical(t.category)}
function saveCategory(t,c){c=canonical(c);localStorage.setItem(txKey(t),c);if(!isP2P(t))localStorage.setItem(merchantKey(t),c)}
function internal(t){const s=source(t).toUpperCase();return /(?:ONLINE BANKING )?TRANSFER (?:TO|FROM) SHARE (?:01|02|31)\b/.test(s)||canonical(t.category)==='Internal Transfer'}
function debtPayment(t){const s=source(t).toUpperCase();return /CAPITAL ONE|CHASE CREDIT CRD|BARCLAYCARD|ACH VISA TYPE: PAYMENT/.test(s)}
function moneyIn(x){return x.tx.filter(t=>t.amount>0&&!internal(t)).reduce((a,t)=>a+t.amount,0)}
function spendingRows(x){return x.tx.filter(t=>t.amount<0&&!internal(t)&&!debtPayment(t))}
function spendCats(x){const o={};spendingRows(x).forEach(t=>{const c=effective(t);o[c]=(o[c]||0)+Math.abs(t.amount)});return o}
function categoryRows(x,c){return x.tx.filter(t=>!internal(t)&&effective(t)===c)}
function categoryNet(x){const o={};x.tx.filter(t=>!internal(t)).forEach(t=>{const c=effective(t);o[c]=(o[c]||0)+t.amount});return o}
function creditCards(k){return CREDIT_HISTORY[k]||[]}
function creditTotal(k){return creditCards(k).reduce((a,c)=>a+Math.max(0,c.balance),0)}
function creditTrend(k){const i=order.indexOf(k);if(i<1)return'No prior month available';const d=creditTotal(k)-creditTotal(order[i-1]);if(Math.abs(d)<.005)return'No change from previous month';return `<span style="color:${d<0?'#5B9A72':'#C43C7A'};font-weight:700">${d<0?'−':'+'}${fmt2(Math.abs(d))} ${d<0?'decrease':'increase'}</span> from previous month`}
function card(l,v,n='',a='',f=''){return`<div class="card ${a?'clickable':''}" ${a?`data-action="${a}" data-filter="${f}"`:''}><div class="label">${l}${a?' · click to verify':''}</div><div class="value">${v}</div>${n?`<div class="note">${n}</div>`:''}</div>`}
function trendText(d,asof){if(d==null)return`<span class="muted">30-day change unavailable</span> · As of ${asof}`;if(Math.abs(d)<.005)return`<span class="muted">No change in last 30 days</span> · As of ${asof}`;return`<span style="color:${d>0?'#5B9A72':'#C43C7A'};font-weight:700">${d>0?'+':'−'}${fmt2(Math.abs(d))} ${d>0?'increase':'decrease'}</span> in last 30 days · As of ${asof}`}
function cashTrend(){const a=order.map(k=>D[k].end),W=760,H=220,p=30,min=Math.min(...a)*.92,max=Math.max(...a)*1.04,pts=a.map((v,i)=>[p+i*(W-2*p)/(a.length-1),H-p-(v-min)/(max-min)*(H-2*p)]);return`<svg viewBox="0 0 ${W} ${H}"><polyline fill="none" stroke="#d8a7b1" stroke-width="5" points="${pts.map(q=>q.join(',')).join(' ')}"/>${pts.map((q,i)=>`<circle cx="${q[0]}" cy="${q[1]}" r="5" fill="white" stroke="#d8a7b1" stroke-width="3"/><text x="${q[0]}" y="${Math.max(14,q[1]-12)}" text-anchor="middle" font-size="11" font-weight="700">${fmt(D[order[i]].end)}</text><text x="${q[0]}" y="212" text-anchor="middle" font-size="11" fill="#746d70">${D[order[i]].label.split(' ')[0]}</text>`).join('')}</svg>`}
const colors=['#c78998','#dfb6be','#ad7d8a','#e7cbd0','#b9929d','#f0dce0','#96707b','#d2a0aa','#e9bfc6','#7f5e67'];
function pie(x){const e=Object.entries(spendCats(x)).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]),total=e.reduce((a,[,v])=>a+v,0),cx=150,cy=150,r=112;let a=-Math.PI/2;let p=[],labs=[];e.forEach(([n,v],i)=>{const pct=v/total*100,a2=a+2*Math.PI*v/total,x1=cx+r*Math.cos(a),y1=cy+r*Math.sin(a),x2=cx+r*Math.cos(a2),y2=cy+r*Math.sin(a2),lg=a2-a>Math.PI?1:0,mid=(a+a2)/2;p.push(`<path d="M ${cx} ${cy} L ${x1} ${y1} A ${r} ${r} 0 ${lg} 1 ${x2} ${y2} Z" fill="${colors[i%colors.length]}"></path>`);if(pct>=2)labs.push(`<text x="${cx+88*Math.cos(mid)}" y="${cy+88*Math.sin(mid)}" text-anchor="middle" font-size="11" font-weight="800" fill="#fff" stroke="#2d2a2b" stroke-width="2.4" paint-order="stroke">${pct.toFixed(1)}%</text>`);a=a2});return`<div class="piebox"><svg viewBox="0 0 300 300">${p.join('')}${labs.join('')}<circle cx="150" cy="150" r="64" fill="#fff"/><text x="150" y="144" text-anchor="middle" font-size="13" fill="#746d70">Bank spending</text><text x="150" y="166" text-anchor="middle" font-size="20" font-weight="700">${fmt(total)}</text></svg></div><div class="pielegend">${e.map(([n,v],i)=>`<div class="clickable" data-action="category" data-filter="${escapeHtml(n)}"><span class="legenddot" style="background:${colors[i%colors.length]}"></span>${escapeHtml(n)} - ${fmt2(v)} - ${(v/total*100).toFixed(1)}%</div>`).join('')}</div>`}
order.forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=D[k].label;sel.appendChild(o)});sel.value=latest;let view='overview',search='';
function overview(){const x=D[latest],prev=D[order.at(-2)],income=order.reduce((a,k)=>a+moneyIn(D[k]),0),spend=order.reduce((a,k)=>a+spendingRows(D[k]).reduce((z,t)=>z+Math.abs(t.amount),0),0),auto=AUTOLOAN.at(-1).balance,cc=creditTotal(latest);return`<div class="grid4">${card('Current cash',fmt(x.end),trendText(x.end-prev.end,x.label),'balance')}${card('Cash growth',fmt(x.change),trendText(x.change,x.label))}${card('Income to date',fmt(income),'External deposits across statements','allIncome')}${card('Bank spending to date',fmt(spend),'Purchases excluding internal transfers and card payments','allSpending')}</div><div class="card section"><h2>Total cash balance trend</h2>${cashTrend()}</div><div class="grid4 section">${card('401(k)',fmt(K401.at(-1).balance),trendText(null,K401.at(-1).date))}${card('Roth IRA',fmt(ROTH.at(-1).balance),trendText(ROTH.at(-1).balance-ROTH.at(-2).balance,ROTH.at(-1).date))}${card('Credit cards',fmt(cc),creditTrend(latest),'creditMonth')}${card('Auto loan',fmt(auto),`Original ${fmt2(AUTO_ORIGINAL)} · ${fmt2(AUTO_PAYMENT)}/month · ${Math.ceil(auto/AUTO_PAYMENT)} payments left`,'autoLoan')}</div>`}
function monthView(){const x=D[sel.value],c=spendCats(x),total=Object.values(c).reduce((a,b)=>a+b,0),net=categoryNet(x),activity=Object.entries(net).filter(([,v])=>Math.abs(v)>.004).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));return`<div class="grid4">${card('Starting cash',fmt(x.start),'Account balances at start','balance','start')}${card('Income in',fmt(moneyIn(x)),'External deposits, regardless of category','income')}${card('Bank spending',fmt(total),'Purchases excluding transfers and card payments','spending')}${card('Ending cash',fmt(x.end),`<span class="${x.change>=0?'positive':'negative'}">Cash ${x.change>=0?'increased':'decreased'} ${fmt(Math.abs(x.change))}</span>`,'balance','end')}</div><div class="two section"><div class="card"><h2>Where my money went</h2>${pie(x)}</div><div class="card"><h2>By category</h2>${activity.map(([n,v])=>`<div class="barrow clickable" data-action="category" data-filter="${escapeHtml(n)}"><div>${escapeHtml(n)}</div><div></div><strong class="${v>0?'positive':'negative'}">${v>0?'+':''}${fmt2(v)}</strong><span class="muted">Net</span></div>`).join('')}</div></div><div class="grid4 section">${card('Credit cards',fmt(creditTotal(sel.value)),creditTrend(sel.value),'creditMonth')}${card('Change in cash',fmt(x.change),x.change>=0?'Cash increased this month':'Cash decreased this month')}<div class="callout" style="grid-column:span 2">Your saved categories override imported statement categories. Internal Charter Oak transfers are excluded. Positive external deposits count as money in even when categorized Education, Shopping, or another category.</div></div>`}
function txRows(a){return a.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`<tr class="clickable txrow" data-id="${encodeURIComponent(txKey(t))}"><td>${dateFmt(t.date)}</td><td><strong>${escapeHtml(source(t))}</strong></td><td><span class="pill">${escapeHtml(effective(t))}</span></td><td>${escapeHtml(t.account)}</td><td class="amount ${t.amount>0?'positive':''}">${fmt2(t.amount)}</td></tr>`).join('')}
function transactions(){const x=D[sel.value],a=x.tx.filter(t=>(source(t)+' '+effective(t)+' '+t.account).toLowerCase().includes(search.toLowerCase())),review=x.tx.filter(t=>effective(t)==='Needs Review').length;return`<div class="card txcard"><div class="txhead"><div><h2>Transactions · ${x.label}</h2><div class="muted">${a.length} filtered entries · ${review} need review</div></div><input id="search" value="${escapeHtml(search)}" placeholder="Search source or category"></div><div class="tablewrap"><table><thead><tr><th>Date</th><th>Source / statement detail</th><th>Category</th><th>Account</th><th>Amount</th></tr></thead><tbody>${txRows(a)}</tbody></table></div></div>`}
function accounts(){const x=D[latest],prev=D[order.at(-2)],auto=AUTOLOAN.at(-1).balance;return`<div class="two"><div class="card"><h2>Cash accounts</h2>${Object.entries(x.endAccounts).map(([n,v])=>`<div class="accountrow"><span>${n}<div class="note">${trendText(v-(prev.endAccounts[n]||0),x.label)}</div></span><strong>${fmt2(v)}</strong></div>`).join('')}</div><div class="card"><h2>Investments</h2><div class="accountrow"><span>401(k)</span><strong>${fmt2(K401.at(-1).balance)}</strong></div><div class="accountrow"><span>Roth IRA</span><strong>${fmt2(ROTH.at(-1).balance)}</strong></div></div><div class="card"><h2>Credit cards</h2>${creditCards(latest).map(c=>`<div class="accountrow"><span>${escapeHtml(c.name)}<div class="note">As of ${c.asof}</div></span><strong>${fmt2(c.balance)}</strong></div>`).join('')}</div><div class="card"><h2>Auto loan</h2><div class="accountrow"><span>Remaining balance</span><strong>${fmt2(auto)}</strong></div><div class="note">Original ${fmt2(AUTO_ORIGINAL)} · ${fmt2(AUTO_PAYMENT)}/month · ${Math.ceil(auto/AUTO_PAYMENT)} payments left</div></div></div>`}
function findTx(id){const k=decodeURIComponent(id);return D[sel.value].tx.find(t=>txKey(t)===k)}
function openEditor(t){const m=document.getElementById('modal');document.getElementById('modalTitle').textContent=source(t);document.getElementById('modalSub').textContent=dateFmt(t.date)+' · '+t.account+' · '+fmt2(t.amount);document.getElementById('modalBody').innerHTML=`<div style="padding:16px 0"><div class="label">Category</div><select id="catEdit" style="width:100%">${USER_CATS.map(c=>`<option ${c===effective(t)?'selected':''}>${c}</option>`).join('')}</select><div class="note" style="margin-top:10px">${isP2P(t)?'Peer-to-peer payments remain Needs Review unless you change this individual transaction.':'Saving also creates a recurring merchant rule for matching transactions.'}</div><button id="saveCat" style="margin-top:16px;padding:10px 16px;border:0;border-radius:10px;background:#2d2a2b;color:white">Save category</button></div>`;m.showModal();document.getElementById('saveCat').onclick=()=>{saveCategory(t,document.getElementById('catEdit').value);m.close();render()}}
function rowsFor(action,filter){const x=D[sel.value];if(action==='income')return x.tx.filter(t=>t.amount>0&&!internal(t));if(action==='spending')return spendingRows(x);if(action==='category')return categoryRows(x,filter);if(action==='allIncome')return order.flatMap(k=>D[k].tx.filter(t=>t.amount>0&&!internal(t)));if(action==='allSpending')return order.flatMap(k=>spendingRows(D[k]));return[]}
function openDetail(action,filter){const m=document.getElementById('modal'),title=document.getElementById('modalTitle'),sub=document.getElementById('modalSub'),body=document.getElementById('modalBody');if(action==='creditMonth'){const a=creditCards(sel.value);title.textContent='Credit cards';sub.textContent=D[sel.value].label;body.innerHTML=`<table><thead><tr><th>Credit card</th><th>Statement date</th><th class="amount">Balance</th></tr></thead><tbody>${a.map(c=>`<tr><td>${escapeHtml(c.name)}</td><td>${c.asof}</td><td class="amount">${fmt2(c.balance)}</td></tr>`).join('')}</tbody></table><div class="modaltotal"><span>Total balance</span><span>${fmt2(creditTotal(sel.value))}</span></div>`;m.showModal();return}if(action==='autoLoan'){title.textContent='Auto loan';sub.textContent='Payment history';body.innerHTML=`<table><thead><tr><th>Date</th><th>Payment</th><th class="amount">Balance</th></tr></thead><tbody>${AUTOLOAN.map(r=>`<tr><td>${r.date}</td><td>${r.payment?fmt2(r.payment):'—'}</td><td class="amount">${fmt2(r.balance)}</td></tr>`).join('')}</tbody></table>`;m.showModal();return}const a=rowsFor(action,filter);title.textContent=filter||({income:'Income deposits',spending:'Bank spending',allIncome:'All income',allSpending:'All bank spending'}[action]||'Details');sub.textContent=action.startsWith('all')?'All statements':D[sel.value].label;const signed=action==='category'||action==='income'||action==='allIncome';body.innerHTML=`<table><thead><tr><th>Date</th><th>Source / description</th><th>Account</th><th class="amount">Amount</th></tr></thead><tbody>${a.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`<tr><td>${dateFmt(t.date)}</td><td>${escapeHtml(source(t))}</td><td>${escapeHtml(t.account)}</td><td class="amount ${t.amount>0?'positive':''}">${fmt2(signed?t.amount:Math.abs(t.amount))}</td></tr>`).join('')}</tbody></table><div class="modaltotal"><span>Total</span><span>${fmt2(a.reduce((z,t)=>z+(signed?t.amount:Math.abs(t.amount)),0))}</span></div>`;m.showModal()}
function wire(){document.querySelectorAll('[data-action]').forEach(e=>e.onclick=()=>openDetail(e.dataset.action,e.dataset.filter||''));document.querySelectorAll('.txrow').forEach(e=>e.onclick=()=>{const t=findTx(e.dataset.id);if(t)openEditor(t)});const q=document.getElementById('search');if(q)q.oninput=()=>{search=q.value;render();const n=document.getElementById('search');n.focus();n.setSelectionRange(n.value.length,n.value.length)}}
function render(){document.getElementById('app').innerHTML=view==='overview'?overview():view==='month'?monthView():view==='transactions'?transactions():accounts();wire()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()});sel.onchange=()=>{search='';render()};document.getElementById('closeModal').onclick=()=>document.getElementById('modal').close();render();
}catch(e){console.error(e);document.getElementById('app').innerHTML='<div class="card"><h2>Dashboard error</h2><p>'+String(e.message||e)+'</p></div>';}})();