(()=>{try{
const R=window.RAW_MONEY_DATA;if(!R)return;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cats=R.cats,merchants=R.merchants,accounts=R.accounts;
const recurringCats=new Set(['Housing','Bills & Utilities','Subscriptions & Digital','Vehicle & Transportation','Health','Education','Debt Payment']);
const legacy={'Rent':'Housing','Phone':'Bills & Utilities','Utilities':'Bills & Utilities','Software / Digital':'Subscriptions & Digital','Auto / Car Wash':'Subscriptions & Digital','Entertainment / Subscriptions':'Subscriptions & Digital','Medical':'Health','Transportation':'Vehicle & Transportation','Credit Card Payment':'Debt Payment'};
const canonical=c=>recurringCats.has(c)?c:(legacy[c]||c);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
const median=a=>{const b=a.slice().sort((x,y)=>x-y),n=b.length;return n%2?b[(n-1)/2]:(b[n/2-1]+b[n/2])/2};
function source(t){return t.description||t.merchant||'Unknown'}
function normalize(s){return String(s).toUpperCase().replace(/WITHDRAWAL|DEPOSIT|RECURRING|DEBIT CARD|CREDIT CARD|MERCH\.?\s*POST:?\s*\d{1,2}\/\d{1,2}|POS\s*#?\d+|ACH|TYPE:.*?(?=CO:|NAME:|$)|DATA:.*?(?=CO:|NAME:|$)|CO:|NAME:/g,' ').replace(/\b\d{2,}\b/g,' ').replace(/[^\w&*.-]+/g,' ').replace(/\s+/g,' ').trim()}
function p2p(s){return /VENMO|ZELLE|CASH ?APP|APPLE CASH|PERSON-TO-PERSON/i.test(s)}
function internal(s,c){return /(?:ONLINE BANKING )?TRANSFER (?:TO|FROM) SHARE (?:01|02|31)\b/i.test(s)||c==='Internal Transfer'}
function debtName(s){const x=String(s).toUpperCase();if(/CAPITAL ONE/.test(x))return'Capital One';if(/CHASE CREDIT CRD/.test(x))return'Amazon / Chase';if(/BARCLAYCARD/.test(x))return'Barclays JetBlue';if(/ACH VISA TYPE: PAYMENT|VISA 5032/.test(x))return'Members 1st Visa';return null}
function effective(t){const s=source(t).toUpperCase();if(debtName(s))return'Debt Payment';if(/NETFLIX\.COM/.test(s))return'Subscriptions & Digital';if(/AMAZON PRIME/.test(s))return'Subscriptions & Digital';if(/JWALES|JOHNSON.*WALES/.test(s))return'Education';if(/INSUR|GEICO|PROGRESSIVE|STATE FARM|ALLSTATE|LIBERTY MUTUAL|NATIONWIDE/.test(s))return'Vehicle & Transportation';const mk='merchantRule:'+normalize(source(t));try{const r=localStorage.getItem(mk);if(r)return canonical(r)}catch{}return canonical(t.category)}
function recurringKey(t){const s=source(t),d=debtName(s);if(d)return'CARD:'+d.toUpperCase();return normalize(s)}
function displayName(key,rows){if(key.startsWith('CARD:'))return key.slice(5).toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()).replace('Amazon / Chase','Amazon / Chase').replace('Barclays Jetblue','Barclays JetBlue');let x=key.replace(/\b(COM|NET|ONLINE|PAYMENT|PURCHASE|AUTOPAY|AUTO PAY)\b/g,' ').replace(/\s+/g,' ').trim();if(/^NETFLIX/.test(x))return'Netflix';if(/^PECO/.test(x))return'PECO';if(/^VERIZON/.test(x))return'Verizon';if(/^T-MOBILE/.test(x))return'T-Mobile';if(/^AMAZON PRIME/.test(x))return'Amazon Prime';const raw=rows?.[0]?source(rows[0]):x;if(/GEICO/i.test(raw))return'GEICO';if(/PROGRESSIVE/i.test(raw))return'Progressive';if(/STATE FARM/i.test(raw))return'State Farm';if(/ALLSTATE/i.test(raw))return'Allstate';return x.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}
function tone(c){return c==='Housing'?'coral':c==='Bills & Utilities'?'lagoon':c==='Subscriptions & Digital'?'orchid':c==='Vehicle & Transportation'?'mango':c==='Health'?'palm':c==='Debt Payment'?'sky':'palm'}
const tx=[];R.order.forEach(k=>{const x=R.months[k];x.tx.forEach((r,i)=>tx.push({date:k+'-'+String(r[0]).padStart(2,'0'),account:accounts[r[1]],merchant:merchants[r[2]],description:merchants[r[2]],amount:+r[3],category:cats[r[4]],month:k,id:k+'-'+i}))});
function isRemoved(key){try{return localStorage.getItem('billHidden:'+key)==='1'}catch{return false}}
function recurring(){const g={};tx.forEach(t=>{const s=source(t),c=effective(t);if(t.amount>=0||p2p(s)||internal(s,t.category))return;const key=recurringKey(t);if(!key||isRemoved(key)||/CASH ?APP|VENMO|ZELLE|PERSON-TO-PERSON/i.test(key))return;const isKnown=recurringCats.has(c)||!!debtName(s)||/SUBSCRIPTION|MONTHLY|INSUR|GEICO|PROGRESSIVE|STATE FARM|ALLSTATE|LIBERTY MUTUAL|NATIONWIDE/i.test(s);if(!isKnown)return;(g[key]??=[]).push({...t,cat:c})});return Object.entries(g).map(([key,rows])=>{const months=[...new Set(rows.map(r=>r.month))];if(months.length<2)return null;const days=rows.map(r=>+r.date.slice(-2)),amounts=rows.map(r=>Math.abs(r.amount)),counts={};rows.forEach(r=>counts[r.cat]=(counts[r.cat]||0)+1);let category=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0];if(key.startsWith('CARD:'))category='Debt Payment';const day=Math.round(median(days)),spread=Math.max(...days)-Math.min(...days),avg=amounts.reduce((a,b)=>a+b,0)/amounts.length,amtSpread=Math.max(...amounts)-Math.min(...amounts),stableAmount=avg?amtSpread/avg<=.35:true;const strongCat=['Housing','Bills & Utilities','Subscriptions & Digital','Debt Payment'].includes(category);if(!strongCat&&spread>14&&!stableAmount)return null;if(!recurringCats.has(category)&&!(spread<=7&&stableAmount&&months.length>=3))return null;return{key,name:displayName(key,rows),category,day,amount:median(amounts)}}).filter(Boolean).sort((a,b)=>a.day-b.day||a.name.localeCompare(b.name))}
let cursor=new Date();cursor=new Date(cursor.getFullYear(),cursor.getMonth(),1);
function monthKey(){return cursor.getFullYear()+'-'+String(cursor.getMonth()+1).padStart(2,'0')}
function dueDate(b){const y=cursor.getFullYear(),m=cursor.getMonth(),last=new Date(y,m+1,0).getDate();let d=b.day;try{const v=localStorage.getItem('billDue:'+b.key);if(v)d=+v}catch{}return new Date(y,m,Math.max(1,Math.min(d,last)))}
function paid(b){try{return localStorage.getItem('billPaid:'+monthKey()+':'+b.key)==='1'}catch{return false}}
function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function calendar(items){const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),by={};items.forEach(b=>(by[b.due.getDate()]??=[]).push(b));let out='';for(let i=0;i<first;i++)out+='<div class="calday blank"></div>';for(let d=1;d<=days;d++){const a=by[d]||[];out+='<div class="calday '+(a.length?'hasbills':'')+'"><span class="daynum">'+d+'</span>'+a.map(b=>'<div class="calevent '+(b.paid?'paid':'')+'" style="--event:var(--'+tone(b.category)+')" title="'+esc(b.name)+' · '+fmt(b.amount)+'"><span></span><small>'+esc(b.name)+'</small></div>').join('')+'</div>'}return out}
function card(label,value,note){return'<div class="card"><div class="label">'+esc(label)+'</div><div class="value">'+esc(value)+'</div><div class="note">'+esc(note)+'</div></div>'}
function renderUpcoming(){document.body.classList.add('upcoming-view');$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view==='upcoming'));const bills=recurring().map(b=>({...b,due:dueDate(b),paid:paid(b)})),unpaid=bills.filter(b=>!b.paid),label=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(cursor),remaining=unpaid.reduce((a,b)=>a+b.amount,0);$('#app').innerHTML='<div class="upcominghead"><div><h2>Upcoming · '+esc(label)+'</h2><div class="muted">Recurring bills, subscriptions, insurance and card payments inferred from statement patterns. Dates are editable.</div></div><div class="upnav"><button class="smallbtn" id="upPrev">‹</button><button class="smallbtn" id="upToday">This month</button><button class="smallbtn" id="upNext">›</button></div></div><div class="grid4 upcomingstats">'+card('Recurring items',String(bills.length),'Bills, subscriptions & card payments')+card('Still due',String(unpaid.length),'Not marked paid')+card('Typical remaining',fmt(remaining),'Based on historical amounts')+card('Paid',String(bills.length-unpaid.length),'Marked paid this month')+'</div><div class="two section upcominglayout"><div class="card"><div class="calendarweek"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="calendargrid">'+calendar(bills)+'</div></div><div class="card reminderpanel"><h2>Upcoming reminders</h2><div class="reminderlist">'+(bills.length?bills.map(b=>'<div class="billrow '+(b.paid?'ispaid':'')+'" style="--bill:var(--'+tone(b.category)+')"><div class="billmain"><span class="billdot"></span><div><strong>'+esc(b.name)+'</strong><div class="billusually">Usually '+fmt(b.amount)+'</div><div class="note">'+esc(b.category)+'</div></div></div><div class="billactions"><label class="duelabel"><span>Due date</span><input class="dueinput" data-bill-key="'+esc(b.key)+'" type="date" value="'+iso(b.due)+'" aria-label="Due date for '+esc(b.name)+'"></label><button class="paidbtn '+(b.paid?'checked':'')+'" data-paid-key="'+esc(b.key)+'" aria-label="'+(b.paid?'Mark unpaid ':'Mark paid ')+esc(b.name)+'" title="'+(b.paid?'Marked paid':'Mark as paid')+'">'+(b.paid?'✓':'○')+'</button><button class="removebill" data-remove-key="'+esc(b.key)+'" aria-label="Remove '+esc(b.name)+' from recurring reminders" title="Remove from recurring reminders">×</button></div></div>').join(''):'<div class="empty">No reliable recurring bills detected yet.</div>')+'</div></div></div>';
$('#upPrev').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);renderUpcoming()};$('#upNext').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);renderUpcoming()};$('#upToday').onclick=()=>{const n=new Date();cursor=new Date(n.getFullYear(),n.getMonth(),1);renderUpcoming()};$$('.dueinput').forEach(i=>i.onchange=()=>{const d=new Date(i.value+'T12:00:00');if(Number.isNaN(d.getTime()))return;try{localStorage.setItem('billDue:'+i.dataset.billKey,String(d.getDate()))}catch{}renderUpcoming()});$$('.paidbtn').forEach(b=>b.onclick=()=>{const key='billPaid:'+monthKey()+':'+b.dataset.paidKey;try{localStorage.getItem(key)==='1'?localStorage.removeItem(key):localStorage.setItem(key,'1')}catch{}renderUpcoming()});$$('.removebill').forEach(b=>b.onclick=()=>{try{localStorage.setItem('billHidden:'+b.dataset.removeKey,'1')}catch{}renderUpcoming()})}
const tabs=$('.tabs');if(tabs&&!$('.tab[data-view="upcoming"]')){const b=document.createElement('button');b.type='button';b.className='tab';b.dataset.view='upcoming';b.textContent='Upcoming';const rules=$('.tab[data-view="rules"]');rules?tabs.insertBefore(b,rules):tabs.appendChild(b);b.onclick=renderUpcoming}
$$('.tab:not([data-view="upcoming"])').forEach(b=>b.addEventListener('click',()=>document.body.classList.remove('upcoming-view')));
}catch(e){console.error('Upcoming view failed:',e)}})();
