const fs=require('fs');
let s=fs.readFileSync('index.html','utf8');
if(!/name="robots"/.test(s))s=s.replace('<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">','<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow">');
s=s.replace('<span class="muted">Month</span><select id="month">','<label class="muted" for="month">Month</label><select id="month" aria-label="Statement month">');
s=s.replace('<div class="tabs">','<div class="tabs" aria-label="Dashboard sections">');
s=s.replaceAll('<button class="tab ','<button type="button" class="tab ');
s=s.replaceAll('<button class="tab"','<button type="button" class="tab"');
s=s.replace('<div id="app">Loading dashboard…</div>','<div id="app" aria-live="polite">Loading dashboard…</div><div id="dataVersion" class="note" style="margin-top:16px;text-align:center"></div>');
s=s.replace('<button class="close" id="closeModal">×</button>','<button type="button" class="close" id="closeModal" aria-label="Close dialog">×</button>');
if(!s.includes(':focus-visible'))s=s.replace('@media(max-width:800px)',`button:focus-visible,select:focus-visible,input:focus-visible{outline:3px solid var(--rose2);outline-offset:2px}\n@media(max-width:800px)`);
const chartTheme=`.card.section>svg polyline{stroke:var(--lagoon)!important}.card.section>svg circle{fill:var(--surface)!important;stroke:var(--coral)!important}.card.section>svg text{fill:var(--muted)!important}.card.section>svg text[font-weight="700"]{fill:var(--ink)!important}.pie-slice:nth-of-type(1){fill:var(--lagoon)!important}.pie-slice:nth-of-type(2){fill:var(--coral)!important}.pie-slice:nth-of-type(3){fill:var(--mango)!important}.pie-slice:nth-of-type(4){fill:var(--palm)!important}.pie-slice:nth-of-type(5){fill:var(--orchid)!important}.pie-slice:nth-of-type(6){fill:var(--sky)!important}.pie-slice:nth-of-type(7){fill:#67b8aa!important}.pie-slice:nth-of-type(8){fill:#f1a37f!important}.pie-slice:nth-of-type(9){fill:#d3bd67!important}.pie-slice:nth-of-type(10){fill:#7fab84!important}.pie-slice:nth-of-type(11){fill:#bd83a3!important}.pie-slice:nth-of-type(12){fill:#72a9b7!important}.piebox svg>circle{fill:var(--surface)!important}.piebox svg>circle+text{fill:var(--muted)!important;stroke:none!important}.piebox svg>circle+text+text{fill:var(--ink)!important;stroke:none!important}`;
if(!s.includes('.pie-slice:nth-of-type(1)'))s=s.replace('@media(max-width:800px)',chartTheme+'\n@media(max-width:800px)');
const upcomingStyles=`
.upcoming-view .controls label[for="month"],.upcoming-view #month{display:none}.upcominghead{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:14px}.upnav{display:flex;gap:7px;align-items:center}.upcomingstats{margin-bottom:4px}.calendarweek,.calendargrid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:6px}.calendarweek{margin-bottom:6px;color:var(--muted);font-size:11px;font-weight:750;text-align:center}.calday{min-height:86px;border:1px solid var(--line);border-radius:12px;padding:7px;background:var(--surface2);overflow:hidden}.calday.blank{visibility:hidden}.calday.hasbills{background:var(--surface)}.daynum{display:block;font-size:11px;font-weight:800;color:var(--muted);margin-bottom:5px}.calevent{display:flex;align-items:center;gap:5px;font-size:10px;line-height:1.15;margin:3px 0;min-width:0}.calevent>span{width:7px;height:7px;border-radius:50%;background:var(--event);flex:0 0 auto}.calevent small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--ink);font-size:10px}.calevent.paid{opacity:.42;text-decoration:line-through}.billrow{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;padding:13px 0;border-bottom:1px solid var(--line)}.billrow:last-child{border-bottom:0}.billrow.ispaid{opacity:.55}.billmain{display:flex;align-items:flex-start;gap:10px;min-width:0}.billdot{width:10px;height:10px;border-radius:50%;background:var(--bill);margin-top:4px;flex:0 0 auto}.billmain strong{display:block;overflow-wrap:anywhere}.billactions{display:flex;gap:8px;align-items:center}.duelabel{display:flex;align-items:center;gap:6px;font-size:11px;color:var(--muted)}.dueinput{padding:7px 9px;min-height:36px;font-size:12px}.paidbtn{white-space:nowrap}.ispaid .paidbtn{border-color:var(--palm);color:var(--good)}
`;
if(!s.includes('.upcominghead'))s=s.replace('@media(max-width:800px)',upcomingStyles+'\n@media(max-width:800px)');
const mobileUpcoming=`@media(max-width:800px){.upcominglayout{grid-template-columns:1fr}.calday{min-height:72px;padding:5px}.calevent small{display:none}.calevent{display:inline-flex;margin-right:2px}.billrow{grid-template-columns:1fr}.billactions{justify-content:space-between}.duelabel{flex:1}.dueinput{width:100%}}\n@media(max-width:520px){.calendarweek,.calendargrid{gap:3px}.calday{min-height:56px;border-radius:9px;padding:4px}.daynum{font-size:10px}.billactions{align-items:stretch;flex-direction:column}.duelabel{display:grid;grid-template-columns:auto 1fr}.paidbtn{width:100%}.upnav{width:100%}.upnav .smallbtn:nth-child(2){flex:1}}\n`;
if(!s.includes('.billactions{align-items:stretch'))s=s.replace('@media(prefers-reduced-motion:reduce)',mobileUpcoming+'@media(prefers-reduced-motion:reduce)');
const prod='<script src="data-static.js?v=20260809a"></script><script src="app.js?v=20260809a"></script><script src="upcoming.js?v=20260809a"></script>';
let start=s.indexOf('<script src="data-static.js');if(start<0)start=s.indexOf('<script src="data-v4-0.js');
const end=s.indexOf('</body>');if(start<0||end<0||start>end)throw new Error('Production script replacement failed');
s=s.slice(0,start)+prod+'\n'+s.slice(end);
if(!s.includes('data-static.js')||!s.includes('upcoming.js')||s.includes('data-v4-0.js'))throw new Error('Production script replacement failed');
fs.writeFileSync('candidate.html',s);
console.log('Wrote candidate.html');
